exchange:
  exchange_id: bybit
trading:
  simulation_mode: true
risk_management:
  order_size_percentage: 1.0
  take_profit_percentage: 2.0
  stop_loss_percentage: 1.0
indicators:
  ema_period: 20
  rsi_period: 14
  macd_short_period: 12
  macd_long_period: 26
  macd_signal_period: 9
  stoch_rsi_period: 14
  stoch_rsi_k_period: 3
  stoch_rsi_d_period: 3
  volatility_window: 20
  volatility_multiplier: 2.0
order_book:
  depth: 25
  imbalance_threshold: 1.5
  volume_cluster_threshold: 10.0
  ob_delta_lookback: 10
  cluster_proximity_threshold_pct: 0.5
trailing_stop:
  trailing_stop_active: true
  trailing_stop_callback: 0.01
signal_weights:
  ema_weight: 1.0
  rsi_weight: 1.0
  macd_weight: 1.0
  stoch_rsi_weight: 1.0
  imbalance_weight: 1.0
  ob_delta_change_weight: 1.0
  spread_weight: 1.0
  cluster_proximity_weight: 1.0
