name: Format Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vale
        run: sudo snap install vale
      - name: Install autopep8
        run: pip install autopep8
      - name: Install Prettier
        run: npm install -g prettier
      - name: Run Universal Formatter
        run: python3 format_all.py
