name: Python Guide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the Python version as needed

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install autopep8 cookiecutter

    - name: Check Python version
      run: python --version

    - name: Lint with flake8
      run: |
        flake8 .
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Format code with black
      run: black --check .

    - name: Fix code with autopep8
      run: autopep8 --in-place --aggressive --aggressive .

    - name: Run security checks with bandit
      run: bandit -r .

    - name: Run type checks with mypy
      run: mypy .

    - name: Generate project template with cookiecutter
      run: cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git

    - name: Run tests with pytest
      run: pytest --cov=.

    - name: Check for outdated dependencies
      run: npx pip-check-updates
